import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default:"Next.js tutorial - Codeevolution",
    template:" %s | codevolution",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        
        <header className="h-auto bg-amber-400 text-2xl text-white">
          <h1>Header</h1>
        </header>

        {children}
        
        <footer className="h-auto bg-gray-500 text-2xl text-white">
            <h1>Footer</h1>
        </footer>
        
        </body>
    </html>
  );
}
